import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { exportDataToGoogleSheets } from "@/lib/googleSheets";

export async function GET() {
  const session = await auth();
  if (!session?.user) {
    return new Response("Unauthorized", { status: 401 });
  }

  try {
    const [employees, leaveRequests, reimbursements, separations, companyEvents] = await Promise.all([
      prisma.employee.findMany({
        include: { department: true },
        orderBy: { employeeId: "asc" },
      }),
      prisma.leaveRequest.findMany({
        include: { employee: true, leaveType: true },
        orderBy: { createdAt: "desc" },
      }),
      prisma.reimbursement.findMany({
        include: { employee: true },
        orderBy: { createdAt: "desc" },
      }),
      prisma.separation.findMany({
        include: { employee: true },
        orderBy: { createdAt: "desc" },
      }),
      prisma.companyEvent.findMany({
        orderBy: { startDate: "asc" },
      }),
    ]);

    // Live export sync directly to Google Sheets worksheets
    try {
      await exportDataToGoogleSheets({
        employees,
        leaveRequests,
        companyEvents,
      });
    } catch (sheetErr) {
      console.error("[Google Sheets] Live export sync failed:", sheetErr);
    }

    let csvContent = "";

    // 1. Header Metadata
    csvContent += `ANTBOX HRMS STATUS REPORT\n`;
    csvContent += `Generated At:,${new Date().toISOString()}\n`;
    csvContent += `Generated By:,${session.user.email ?? "System"}\n\n`;

    // 2. Section: Headcount & Employees Overview
    csvContent += `SECTION 1: HEADCOUNT OVERVIEW (ACTIVE & ONBOARDING)\n`;
    csvContent += `Employee ID,First Name,Last Name,Official Email,Personal Email,Phone,Date of Birth,Gender,Blood Group,Permanent Address,City,State,Pincode,Emergency Contact Name,Emergency Contact Phone,Designation,Department,Employment Type,Status,Joining Date,CTC,Basic Salary,HRA,Special Allowance,PF,Professional Tax,Bank Name,Bank Account Number,IFSC Code,PAN,UAN\n`;
    employees.forEach((emp) => {
      const personalEmail = emp.personalEmail || "—";
      const phone = emp.phone || "—";
      const dob = emp.dateOfBirth ? new Date(emp.dateOfBirth).toISOString().slice(0, 10) : "—";
      const gender = emp.gender || "—";
      const bloodGroup = emp.bloodGroup || "—";
      const permAddress = emp.permanentAddress ? emp.permanentAddress.replace(/"/g, '""') : "—";
      const city = emp.city || "—";
      const state = emp.state || "Odisha";
      const pincode = emp.pincode || "—";
      const emergencyContact = emp.emergencyContact || "—";
      const emergencyPhone = emp.emergencyPhone || "—";
      const joiningDate = emp.joiningDate ? new Date(emp.joiningDate).toISOString().slice(0, 10) : "—";
      const ctc = emp.ctc ?? 0;
      const basic = emp.basicSalary ?? 0;
      const hra = emp.hra ?? 0;
      const special = emp.specialAllowance ?? 0;
      const pf = emp.pf ?? 0;
      const pt = emp.professionalTax ?? 200;
      const bankName = emp.bankName || "—";
      const bankAccountNo = emp.bankAccountNo || "—";
      const ifsc = emp.ifscCode || "—";
      const pan = emp.pan || "—";
      const uan = emp.uan || "—";

      csvContent += `"${emp.employeeId}","${emp.firstName}","${emp.lastName}","${emp.email}","${personalEmail}","${phone}","${dob}","${gender}","${bloodGroup}","${permAddress}","${city}","${state}","${pincode}","${emergencyContact}","${emergencyPhone}","${emp.designation}","${emp.department?.name ?? "—"}","${emp.employmentType}","${emp.status}","${joiningDate}",${ctc},${basic},${hra},${special},${pf},${pt},"${bankName}","${bankAccountNo}","${ifsc}","${pan}","${uan}"\n`;
    });
    csvContent += `\n`;

    // 3. Section: Leave Requests
    csvContent += `SECTION 2: RECENT LEAVE REQUESTS\n`;
    csvContent += `Employee ID,Employee Name,Leave Type,Start Date,End Date,Days,Reason,Status\n`;
    leaveRequests.forEach((req) => {
      const empName = `${req.employee?.firstName ?? ""} ${req.employee?.lastName ?? ""}`;
      const startDate = req.startDate ? new Date(req.startDate).toISOString().slice(0, 10) : "—";
      const endDate = req.endDate ? new Date(req.endDate).toISOString().slice(0, 10) : "—";
      csvContent += `"${req.employee?.employeeId ?? "—"}","${empName}","${req.leaveType?.name ?? "—"}","${startDate}","${endDate}",${req.days},"${req.reason.replace(/"/g, '""')}","${req.status}"\n`;
    });
    csvContent += `\n`;

    // 4. Section: Reimbursements
    csvContent += `SECTION 3: REIMBURSEMENT CLAIMS\n`;
    csvContent += `Employee ID,Employee Name,Title,Category,Amount,Currency,Date,Status\n`;
    reimbursements.forEach((r) => {
      const empName = `${r.employee?.firstName ?? ""} ${r.employee?.lastName ?? ""}`;
      const claimDate = r.date ? new Date(r.date).toISOString().slice(0, 10) : "—";
      csvContent += `"${r.employee?.employeeId ?? "—"}","${empName}","${r.title.replace(/"/g, '""')}","${r.category}",${r.amount},"${r.currency}","${claimDate}","${r.status}"\n`;
    });
    csvContent += `\n`;

    // 5. Section: Separations
    csvContent += `SECTION 4: SEPARATION INITIATIONS\n`;
    csvContent += `Employee ID,Employee Name,Status,Notice Days,Reason,Initiated At\n`;
    separations.forEach((s) => {
      const empName = `${s.employee?.firstName ?? ""} ${s.employee?.lastName ?? ""}`;
      const initiatedAt = s.initiatedAt ? new Date(s.initiatedAt).toISOString().slice(0, 10) : "—";
      csvContent += `"${s.employee?.employeeId ?? "—"}","${empName}","${s.status}",${s.noticeDays},"${s.reason.replace(/"/g, '""')}","${initiatedAt}"\n`;
    });

    return new Response(csvContent, {
      status: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="AntBox_HRMS_Status_Report_${new Date().toISOString().slice(0, 10)}.csv"`,
      },
    });
  } catch (error) {
    console.error("Failed to generate report:", error);
    return new Response("Internal Server Error", { status: 500 });
  }
}
