import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";

export async function GET() {
  const session = await auth();
  if (!session?.user) {
    return new Response("Unauthorized", { status: 401 });
  }

  try {
    const [employees, leaveRequests, reimbursements, separations] = await Promise.all([
      prisma.employee.findMany({
        include: { department: true },
        orderBy: { employeeId: "asc" },
      }),
      prisma.leaveRequest.findMany({
        include: { employee: true, leaveType: true },
        orderBy: { createdAt: "desc" },
      }),
      prisma.reimbursement.findMany({
        include: { employee: true },
        orderBy: { createdAt: "desc" },
      }),
      prisma.separation.findMany({
        include: { employee: true },
        orderBy: { createdAt: "desc" },
      }),
    ]);

    let csvContent = "";

    // 1. Header Metadata
    csvContent += `ANTBOX HRMS STATUS REPORT\n`;
    csvContent += `Generated At:,${new Date().toISOString()}\n`;
    csvContent += `Generated By:,${session.user.email ?? "System"}\n\n`;

    // 2. Section: Headcount & Employees Overview
    csvContent += `SECTION 1: HEADCOUNT OVERVIEW (ACTIVE & ONBOARDING)\n`;
    csvContent += `Employee ID,First Name,Last Name,Official Email,Personal Email,Phone,Designation,Department,Type,Status,Joining Date,City,State,CTC\n`;
    employees.forEach((emp) => {
      const joiningDate = emp.joiningDate ? new Date(emp.joiningDate).toISOString().slice(0, 10) : "—";
      const personalEmail = emp.personalEmail || "—";
      const phone = emp.phone || "—";
      const city = emp.city || "—";
      const state = emp.state || "Odisha";
      const ctc = emp.ctc ?? 0;
      csvContent += `"${emp.employeeId}","${emp.firstName}","${emp.lastName}","${emp.email}","${personalEmail}","${phone}","${emp.designation}","${emp.department?.name ?? "—"}","${emp.employmentType}","${emp.status}","${joiningDate}","${city}","${state}",${ctc}\n`;
    });
    csvContent += `\n`;

    // 3. Section: Leave Requests
    csvContent += `SECTION 2: RECENT LEAVE REQUESTS\n`;
    csvContent += `Employee ID,Employee Name,Leave Type,Start Date,End Date,Days,Reason,Status\n`;
    leaveRequests.forEach((req) => {
      const empName = `${req.employee?.firstName ?? ""} ${req.employee?.lastName ?? ""}`;
      const startDate = req.startDate ? new Date(req.startDate).toISOString().slice(0, 10) : "—";
      const endDate = req.endDate ? new Date(req.endDate).toISOString().slice(0, 10) : "—";
      csvContent += `"${req.employee?.employeeId ?? "—"}","${empName}","${req.leaveType?.name ?? "—"}","${startDate}","${endDate}",${req.days},"${req.reason.replace(/"/g, '""')}","${req.status}"\n`;
    });
    csvContent += `\n`;

    // 4. Section: Reimbursements
    csvContent += `SECTION 3: REIMBURSEMENT CLAIMS\n`;
    csvContent += `Employee ID,Employee Name,Title,Category,Amount,Currency,Date,Status\n`;
    reimbursements.forEach((r) => {
      const empName = `${r.employee?.firstName ?? ""} ${r.employee?.lastName ?? ""}`;
      const claimDate = r.date ? new Date(r.date).toISOString().slice(0, 10) : "—";
      csvContent += `"${r.employee?.employeeId ?? "—"}","${empName}","${r.title.replace(/"/g, '""')}","${r.category}",${r.amount},"${r.currency}","${claimDate}","${r.status}"\n`;
    });
    csvContent += `\n`;

    // 5. Section: Separations
    csvContent += `SECTION 4: SEPARATION INITIATIONS\n`;
    csvContent += `Employee ID,Employee Name,Status,Notice Days,Reason,Initiated At\n`;
    separations.forEach((s) => {
      const empName = `${s.employee?.firstName ?? ""} ${s.employee?.lastName ?? ""}`;
      const initiatedAt = s.initiatedAt ? new Date(s.initiatedAt).toISOString().slice(0, 10) : "—";
      csvContent += `"${s.employee?.employeeId ?? "—"}","${empName}","${s.status}",${s.noticeDays},"${s.reason.replace(/"/g, '""')}","${initiatedAt}"\n`;
    });

    return new Response(csvContent, {
      status: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="AntBox_HRMS_Status_Report_${new Date().toISOString().slice(0, 10)}.csv"`,
      },
    });
  } catch (error) {
    console.error("Failed to generate report:", error);
    return new Response("Internal Server Error", { status: 500 });
  }
}
