import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";

export async function GET() {
  const session = await auth();
  if (!session?.user) {
    return new Response("Unauthorized", { status: 401 });
  }

  try {
    const [employees, grievances, leaveRequests, itTasks] = await Promise.all([
      prisma.employee.findMany({
        include: { department: true },
        orderBy: { employeeId: "asc" },
      }),
      prisma.grievance.findMany({
        orderBy: { createdAt: "desc" },
      }),
      prisma.leaveRequest.findMany({
        include: { employee: true, leaveType: true },
        orderBy: { createdAt: "desc" },
      }),
      prisma.iTTask.findMany({
        include: { employee: true },
        orderBy: { createdAt: "desc" },
      }),
    ]);

    // Construct CSV content
    let csvContent = "";

    // 1. Header: Metadata
    csvContent += `ANTBOX HRMS STATUS REPORT\n`;
    csvContent += `Generated At:,${new Date().toISOString()}\n`;
    csvContent += `Generated By:,${session.user.email ?? "System"}\n\n`;

    // 2. Section: Headcount Overview
    csvContent += `SECTION 1: HEADCOUNT OVERVIEW\n`;
    csvContent += `Employee ID,First Name,Last Name,Email,Designation,Department,Type,Status,Joining Date\n`;
    employees.forEach((emp) => {
      const joiningDate = emp.joiningDate ? new Date(emp.joiningDate).toISOString().slice(0, 10) : "—";
      csvContent += `"${emp.employeeId}","${emp.firstName}","${emp.lastName}","${emp.email}","${emp.designation}","${emp.department?.name ?? "—"}","${emp.employmentType}","${emp.status}","${joiningDate}"\n`;
    });
    csvContent += `\n`;

    // 3. Section: Leave Requests
    csvContent += `SECTION 2: RECENT LEAVE REQUESTS\n`;
    csvContent += `Employee,Leave Type,Start Date,End Date,Days,Reason,Status\n`;
    leaveRequests.forEach((req) => {
      const empName = `${req.employee?.firstName ?? ""} ${req.employee?.lastName ?? ""}`;
      const startDate = req.startDate ? new Date(req.startDate).toISOString().slice(0, 10) : "—";
      const endDate = req.endDate ? new Date(req.endDate).toISOString().slice(0, 10) : "—";
      csvContent += `"${empName}","${req.leaveType?.name ?? "—"}","${startDate}","${endDate}",${req.days},"${req.reason.replace(/"/g, '""')}","${req.status}"\n`;
    });
    csvContent += `\n`;

    // 4. Section: Grievances
    csvContent += `SECTION 3: WORKSPACE GRIEVANCES\n`;
    csvContent += `Ticket No,Subject,Category,Priority,Status,Created At\n`;
    grievances.forEach((grv) => {
      const createdAt = grv.createdAt ? new Date(grv.createdAt).toISOString().slice(0, 10) : "—";
      csvContent += `"${grv.ticketNo}","${grv.subject.replace(/"/g, '""')}","${grv.category}","${grv.priority}","${grv.status}","${createdAt}"\n`;
    });

    // 5. Section: IT Tasks
    csvContent += `\nSECTION 4: IT OPERATIONS TASKS\n`;
    csvContent += `Employee,Task Type,Status,Details,Created At\n`;
    itTasks.forEach((task) => {
      const empName = `${task.employee?.firstName ?? ""} ${task.employee?.lastName ?? ""}`;
      const createdAt = task.createdAt ? new Date(task.createdAt).toISOString().slice(0, 10) : "—";
      csvContent += `"${empName}","${task.taskType}","${task.status}","${(task.details ?? "").replace(/"/g, '""')}","${createdAt}"\n`;
    });

    return new Response(csvContent, {
      status: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="AntBox_HRMS_Status_Report_${new Date().toISOString().slice(0, 10)}.csv"`,
      },
    });
  } catch (error) {
    console.error("Failed to generate report:", error);
    return new Response("Internal Server Error", { status: 500 });
  }
}
